repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: pnpm-lint
        name: Biome lint
        entry: pnpm
        args: ["lint"]
        language: system
        pass_filenames: false
        always_run: true

      - id: pnpm-format
        name: Biome format
        entry: pnpm
        args: ["format"]
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
        exclude: 'tsconfig.json'
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
