packages:
  - packages/*
onlyBuiltDependencies:
  - '@biomejs/biome'
  - core-js
  - esbuild
overrides:
  chargebee-init: link:packages/cli
  '@chargebee/express': link:packages/express
  '@chargebee/nextjs': link:packages/nextjs
