export const CHARGEBEE_ERROR_CODES = {
	ALREADY_SUBSCRIBED: "ALREADY_SUBSCRIBED_TO_THIS_PLAN",
	SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
	PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
	CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
	ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",
	UNAUTHORIZED_REFERENCE: "UNAUTHORIZED_REFERENCE",
	ACTIVE_SUBSCRIPTION_EXISTS: "ACTIVE_SUBSCRIPTION_EXISTS",
	ORG_HAS_ACTIVE_SUBSCRIPTIONS: "ORG_HAS_ACTIVE_SUBSCRIPTIONS",
	WEBHOOK_VERIFICATION_FAILED: "WEBHOOK_VERIFICATION_FAILED",
	EMAIL_VERIFICATION_REQUIRED: "EMAIL_VERIFICATION_REQUIRED",
	UNABLE_TO_CREATE_CUSTOMER: "UNABLE_TO_CREATE_CUSTOMER",
	ORGANIZATION_SUBSCRIPTION_NOT_ENABLED:
		"ORGANIZATION_SUBSCRIPTION_NOT_ENABLED",
} as const;
